# Gradle
org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.configuration-cache=true
# Loom
fabric.loom.multiProjectOptimisation=true
# Mod Metadata
group=io.github.slimeistdev
user=techno-sam
slug=crystalline-sky
modId=crystalline_sky
modName=Crystalline Sky
modDescription= Crystallizes the heavens into block form. For all your sky-in-a-cave needs.
authors=Slimeist
contributors=
license=EUPL 1.2 or later
# Mod Version
modVersion=0.1.0
# Branch Metadata
branchName=fabric-1.21.8
compatibleVersions=1.21.8
compatibleLoaders=fabric

# mod compat
enable_sodium=true
